"""Reusable fallback regex selectors that may enter canonical format specs."""

from __future__ import annotations


SELECTOR_PATTERNS: dict[str, dict[str, object]] = {
    "heading.level_1": {
        "patterns": [r"^第[一二三四五六七八九十百]+章(?:\s|$)", r"^\d+\s+\S"],
        "positive": ["第一章 绪论", "1 绪论"],
        "negative": ["第一节 研究背景", "1.1 研究背景"],
        "priority": 80,
    },
    "heading.level_2": {
        "patterns": [r"^第[一二三四五六七八九十百]+节(?:\s|$)", r"^\d+\.\d+(?!\.\d)\s*\S"],
        "positive": ["第一节 背景", "1.1 研究背景"],
        "negative": ["第一章 绪论", "1.1.1 研究方法"],
        "priority": 75,
    },
    "heading.level_3": {
        "patterns": [r"^\d+\.\d+\.\d+\s*\S"],
        "positive": ["1.1.1 研究方法"],
        "negative": ["1.1 研究背景"],
        "priority": 70,
    },
    "table_of_contents.level_1.number": {
        "patterns": [r"^(\d+)(?=\s|[^\d.])"],
        "positive": ["1 绪论"],
        "negative": ["1.1 研究背景"],
        "priority": 89,
        "match_scope": "text_span",
        "within_target": "table_of_contents.level_1",
        "capture_group": 1,
    },
    "table_of_contents.level_2.number": {
        "patterns": [r"^(\d+\.\d+)(?=\s|[^\d.])"],
        "positive": ["1.1 研究背景"],
        "negative": ["1.1.1 研究方法"],
        "priority": 89,
        "match_scope": "text_span",
        "within_target": "table_of_contents.level_2",
        "capture_group": 1,
    },
    "table_of_contents.level_3.number": {
        "patterns": [r"^(\d+\.\d+\.\d+)(?=\s|[^\d.])"],
        "positive": ["1.1.1 研究方法"],
        "negative": ["1.1 研究背景"],
        "priority": 89,
        "match_scope": "text_span",
        "within_target": "table_of_contents.level_3",
        "capture_group": 1,
    },
    "abstract.zh.heading": {
        "patterns": [r"^(?:摘\s*要|中文摘要)$"],
        "positive": ["摘要", "摘 要"],
        "negative": ["摘要正文"],
        "priority": 90,
    },
    "abstract.en.heading": {
        "patterns": [r"^(?:Abstract|ABSTRACT)$"],
        "positive": ["Abstract", "ABSTRACT"],
        "negative": ["Abstract text"],
        "priority": 90,
    },
    "keywords.zh": {
        "patterns": [r"^关键词\s*[：:]"],
        "positive": ["关键词：格式识别；论文"],
        "negative": ["本文关键词包括"],
        "priority": 85,
    },
    "keywords.zh.label": {
        "patterns": [r"^(关键词)\s*[：:]"],
        "positive": ["关键词：格式识别；论文"],
        "negative": ["本文关键词包括"],
        "priority": 92,
        "match_scope": "text_span",
        "within_target": "keywords.zh",
        "capture_group": 1,
    },
    "keywords.zh.content": {
        "patterns": [r"^关键词\s*[：:]\s*(.+)$"],
        "positive": ["关键词：格式识别；论文"],
        "negative": ["关键词："],
        "priority": 91,
        "match_scope": "text_span",
        "within_target": "keywords.zh",
        "capture_group": 1,
    },
    "keywords.en": {
        "patterns": [r"^(?:Key\s*words|Keywords)\s*[：:]"],
        "positive": ["Keywords: formatting; thesis"],
        "negative": ["The keywords are"],
        "priority": 85,
    },
    "keywords.en.label": {
        "patterns": [r"^((?:Key\s*words|Keywords))\s*[：:]"],
        "positive": ["Keywords: formatting; thesis"],
        "negative": ["The keywords are"],
        "priority": 92,
        "match_scope": "text_span",
        "within_target": "keywords.en",
        "capture_group": 1,
    },
    "keywords.en.content": {
        "patterns": [r"^(?:Key\s*words|Keywords)\s*[：:]\s*(.+)$"],
        "positive": ["Keywords: formatting; thesis"],
        "negative": ["Keywords:"],
        "priority": 91,
        "match_scope": "text_span",
        "within_target": "keywords.en",
        "capture_group": 1,
    },
    "cover.student_id": {
        "patterns": [r"^学号\s*[：:]?"],
        "positive": ["学号：20260001"],
        "negative": ["学生姓名：张三"],
        "priority": 90,
    },
    "cover.confidentiality": {
        "patterns": [r"^密级\s*[：:]?"],
        "positive": ["密级：公开"],
        "negative": ["学号：20260001"],
        "priority": 90,
    },
    "cover.department": {
        "patterns": [r"^(?:院|院系|院（系）|学院|系)\s*(?:名称)?\s*[：:]"],
        "positive": ["院（系）名称：计算机学院"],
        "negative": ["专业名称：计算机科学"],
        "priority": 88,
    },
    "cover.major": {
        "patterns": [r"^专业(?:名称)?\s*[：:]"],
        "positive": ["专业名称：计算机科学"],
        "negative": ["院（系）名称：计算机学院"],
        "priority": 88,
    },
    "cover.student_name": {
        "patterns": [r"^学生姓名\s*[：:]"],
        "positive": ["学生姓名：张三"],
        "negative": ["指导教师：李老师"],
        "priority": 88,
    },
    "cover.supervisor": {
        "patterns": [r"^指导教师\s*[：:]"],
        "positive": ["指导教师：李老师"],
        "negative": ["学生姓名：张三"],
        "priority": 88,
    },
    "document.header.institution": {
        "patterns": [r"([\u4e00-\u9fff]{2,30}(?:大学|学院|学校|研究院))"],
        "positive": ["华东理工大学 硕士学位论文"],
        "negative": ["硕士学位论文"],
        "priority": 92,
        "match_scope": "text_span",
        "within_target": "document.header",
        "capture_group": 1,
    },
    "document.header.other": {
        "patterns": [],
        "positive": [],
        "negative": [],
        "priority": 91,
        "match_scope": "text_span",
        "within_target": "document.header",
        "exclude_targets": ["document.header.institution"],
    },
    "figure.caption": {
        "patterns": [r"^图\s*\d+(?:[-—.]\d+)*\s*\S", r"^(?:Figure|Fig\.)\s*\d+(?:[-—.]\d+)*\s*\S"],
        "positive": ["图 2-1 系统结构", "Figure 2.1 System"],
        "negative": ["如图所示"],
        "priority": 75,
    },
    "figure.caption.zh": {
        "patterns": [r"^图\s*\d+(?:[-—.]\d+)*\s*\S"],
        "positive": ["图 2-1 系统结构"],
        "negative": ["Figure 2.1 System", "如图所示"],
        "priority": 76,
    },
    "figure.caption.en": {
        "patterns": [r"^(?:Figure|Fig\.)\s*\d+(?:[-—.]\d+)*\s*\S"],
        "positive": ["Fig. 2.1 System"],
        "negative": ["图 2-1 系统结构"],
        "priority": 76,
    },
    "table.caption": {
        "patterns": [r"^表\s*\d+(?:[-—.]\d+)*\s*\S", r"^Table\s*\d+(?:[-—.]\d+)*\s*\S"],
        "positive": ["表 2-1 实验结果", "Table 2.1 Results"],
        "negative": ["下表说明"],
        "priority": 75,
    },
    "table.caption.zh": {
        "patterns": [r"^表\s*\d+(?:[-—.]\d+)*\s*\S"],
        "positive": ["表 2-1 实验结果"],
        "negative": ["Table 2.1 Results", "下表说明"],
        "priority": 76,
    },
    "table.caption.en": {
        "patterns": [r"^Table\s*\d+(?:[-—.]\d+)*\s*\S"],
        "positive": ["Table 2.1 Results"],
        "negative": ["表 2-1 实验结果"],
        "priority": 76,
    },
    "table.caption.number": {
        "patterns": [r"^(?:表|Table)\s*(\d+(?:[-—.]\d+)*)"],
        "positive": ["表2.4 实验结果", "Table 2.4 Results"],
        "negative": ["下表说明"],
        "priority": 88,
        "match_scope": "text_span",
        "within_target": "table.caption",
        "capture_group": 1,
    },
    "references.heading": {
        "patterns": [r"^参考文献$", r"^References$"],
        "positive": ["参考文献", "References"],
        "negative": ["参考文献综述"],
        "priority": 90,
    },
    "references.entry": {
        "patterns": [r"^\[\d+\]\s*\S", r"^\d+[.、]\s*\S"],
        "positive": ["[1] 张三. 论文题名", "1. Zhang. Title"],
        "negative": ["第一章 绪论"],
        "priority": 65,
    },
    "references.entry.journal": {
        "patterns": [r"^\[?\d+\]?\s*.+\[J\]"],
        "positive": ["[1] 张三. 文章题目[J]. 期刊名"],
        "negative": ["[1] 张三. 书名[M]. 出版社"],
        "priority": 78,
    },
    "references.entry.book": {
        "patterns": [r"^\[?\d+\]?\s*.+\[M\]"],
        "positive": ["[1] 张三. 书名[M]. 出版社"],
        "negative": ["[1] 张三. 文章题目[J]. 期刊名"],
        "priority": 78,
    },
    "references.entry.proceedings": {
        "patterns": [r"^\[?\d+\]?\s*.+\[(?:A|C)\]"],
        "positive": ["[1] 张三. 文章题目[A]. 论文集名[C]"],
        "negative": ["[1] 张三. 论文题目[D]"],
        "priority": 78,
    },
    "references.entry.thesis": {
        "patterns": [r"^\[?\d+\]?\s*.+\[D\]"],
        "positive": ["[1] 张三. 论文题目[D]. 武汉"],
        "negative": ["[1] 张三. 报告题目[R]"],
        "priority": 78,
    },
    "references.entry.report": {
        "patterns": [r"^\[?\d+\]?\s*.+\[R\]"],
        "positive": ["[1] 张三. 报告题目[R]. 武汉"],
        "negative": ["[1] 张三. 论文题目[D]"],
        "priority": 78,
    },
    "references.entry.patent": {
        "patterns": [r"^\[?\d+\]?\s*.+\[P\]"],
        "positive": ["[1] 张三. 专利名称[P]. 2020"],
        "negative": ["[1] GB 123. 标准名称[S]"],
        "priority": 78,
    },
    "references.entry.standard": {
        "patterns": [r"^\[?\d+\]?\s*.+\[S\]"],
        "positive": ["[1] GB 123. 标准名称[S]. 北京"],
        "negative": ["[1] 张三. 专利名称[P]"],
        "priority": 78,
    },
    "references.entry.newspaper": {
        "patterns": [r"^\[?\d+\]?\s*.+\[N\]"],
        "positive": ["[1] 张三. 文章题目[N]. 人民日报"],
        "negative": ["[1] 张三. 文章题目[J]. 期刊名"],
        "priority": 78,
    },
    "references.entry.electronic": {
        "patterns": [r"^\[?\d+\]?\s*.+\[(?:DB|M|CP|J|EB)/(?:OL|MT|CD|DK)\]"],
        "positive": ["[1] 数据库[DB/OL]. https://example.com"],
        "negative": ["[1] 张三. 文章题目[J]. 期刊名"],
        "priority": 78,
    },
    "appendix.heading": {
        "patterns": [r"^附录\s*[A-Z一二三四五六七八九十\d]*(?:\s|$)", r"^Appendix\s*[A-Z\d]*(?:\s|$)"],
        "positive": ["附录 A 数据", "Appendix A Data"],
        "negative": ["参见附录A"],
        "priority": 85,
    },
    "acknowledgements.heading": {
        "patterns": [r"^(?:致谢|谢辞)$"],
        "positive": ["致谢"],
        "negative": ["致谢词正文"],
        "priority": 90,
    },
}
